<?php
/**
 * SocialProvidersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\OpenApi\Management\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Lock\Client\OpenApi\Management\ApiException;
use Lock\Client\OpenApi\Management\Configuration;
use Lock\Client\OpenApi\Management\HeaderSelector;
use Lock\Client\OpenApi\Management\ObjectSerializer;

/**
 * SocialProvidersApi Class Doc Comment
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SocialProvidersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createSocialProvider' => [
            'application/json',
        ],
        'deleteSocialProvider' => [
            'application/json',
        ],
        'getSocialProvider' => [
            'application/json',
        ],
        'listSocialProviders' => [
            'application/json',
        ],
        'patchSocialProvider' => [
            'application/json',
        ],
        'updateSocialProvider' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createSocialProvider
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Management\Model\CreateSocialProviderData $createSocialProviderData createSocialProviderData (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\ValidationError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError
     */
    public function createSocialProvider($realm, $createSocialProviderData, string $contentType = self::contentTypes['createSocialProvider'][0])
    {
        list($response) = $this->createSocialProviderWithHttpInfo($realm, $createSocialProviderData, $contentType);
        return $response;
    }

    /**
     * Operation createSocialProviderWithHttpInfo
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Management\Model\CreateSocialProviderData $createSocialProviderData (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\ValidationError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSocialProviderWithHttpInfo($realm, $createSocialProviderData, string $contentType = self::contentTypes['createSocialProvider'][0])
    {
        $request = $this->createSocialProviderRequest($realm, $createSocialProviderData, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'createSocialProvider'
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Management\Model\CreateSocialProviderData $createSocialProviderData (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSocialProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createSocialProviderRequest($realm, $createSocialProviderData, string $contentType = self::contentTypes['createSocialProvider'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling createSocialProvider'
            );
        }

        // verify the required parameter 'createSocialProviderData' is set
        if ($createSocialProviderData === null || (is_array($createSocialProviderData) && count($createSocialProviderData) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $createSocialProviderData when calling createSocialProvider'
            );
        }


        $resourcePath = '/v1/realms/{realm}/social-providers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createSocialProviderData)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($createSocialProviderData), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $createSocialProviderData;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteSocialProvider
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider socialProvider (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteSocialProvider($realm, $socialProvider, string $contentType = self::contentTypes['deleteSocialProvider'][0])
    {
        $this->deleteSocialProviderWithHttpInfo($realm, $socialProvider, $contentType);
    }

    /**
     * Operation deleteSocialProviderWithHttpInfo
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSocialProviderWithHttpInfo($realm, $socialProvider, string $contentType = self::contentTypes['deleteSocialProvider'][0])
    {
        $request = $this->deleteSocialProviderRequest($realm, $socialProvider, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'deleteSocialProvider'
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSocialProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteSocialProviderRequest($realm, $socialProvider, string $contentType = self::contentTypes['deleteSocialProvider'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling deleteSocialProvider'
            );
        }

        // verify the required parameter 'socialProvider' is set
        if ($socialProvider === null || (is_array($socialProvider) && count($socialProvider) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $socialProvider when calling deleteSocialProvider'
            );
        }


        $resourcePath = '/v1/realms/{realm}/social-providers/{social_provider}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }
        // path params
        if ($socialProvider !== null) {
            $resourcePath = str_replace(
                '{social_provider}',
                ObjectSerializer::toPathValue($socialProvider),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSocialProvider
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider socialProvider (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError
     */
    public function getSocialProvider($realm, $socialProvider, string $contentType = self::contentTypes['getSocialProvider'][0])
    {
        list($response) = $this->getSocialProviderWithHttpInfo($realm, $socialProvider, $contentType);
        return $response;
    }

    /**
     * Operation getSocialProviderWithHttpInfo
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSocialProviderWithHttpInfo($realm, $socialProvider, string $contentType = self::contentTypes['getSocialProvider'][0])
    {
        $request = $this->getSocialProviderRequest($realm, $socialProvider, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'getSocialProvider'
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSocialProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSocialProviderRequest($realm, $socialProvider, string $contentType = self::contentTypes['getSocialProvider'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling getSocialProvider'
            );
        }

        // verify the required parameter 'socialProvider' is set
        if ($socialProvider === null || (is_array($socialProvider) && count($socialProvider) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $socialProvider when calling getSocialProvider'
            );
        }


        $resourcePath = '/v1/realms/{realm}/social-providers/{social_provider}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }
        // path params
        if ($socialProvider !== null) {
            $resourcePath = str_replace(
                '{social_provider}',
                ObjectSerializer::toPathValue($socialProvider),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listSocialProviders
     *
     * @param  string $realm The realm slug (required)
     * @param  string[]|null $sort Available sorts are &#x60;key&#x60;, &#x60;driver&#x60;, &#x60;created_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-key&#x60;. (optional)
     * @param  string[]|null $filterKey Filter by &#x60;key&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDriver Filter by &#x60;driver&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterEnabled Filter by &#x60;enabled&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  int|null $page The page number to retrieve. (optional)
     * @param  int|null $perPage The number of items to retrieve per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSocialProviders'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Management\Model\SocialProviderCollection|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError|\Lock\Client\OpenApi\Management\Model\ValidationError
     */
    public function listSocialProviders($realm, $sort = null, $filterKey = null, $filterDriver = null, $filterEnabled = null, $page = null, $perPage = null, string $contentType = self::contentTypes['listSocialProviders'][0])
    {
        list($response) = $this->listSocialProvidersWithHttpInfo($realm, $sort, $filterKey, $filterDriver, $filterEnabled, $page, $perPage, $contentType);
        return $response;
    }

    /**
     * Operation listSocialProvidersWithHttpInfo
     *
     * @param  string $realm The realm slug (required)
     * @param  string[]|null $sort Available sorts are &#x60;key&#x60;, &#x60;driver&#x60;, &#x60;created_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-key&#x60;. (optional)
     * @param  string[]|null $filterKey Filter by &#x60;key&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDriver Filter by &#x60;driver&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterEnabled Filter by &#x60;enabled&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  int|null $page The page number to retrieve. (optional)
     * @param  int|null $perPage The number of items to retrieve per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSocialProviders'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Management\Model\SocialProviderCollection|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError|\Lock\Client\OpenApi\Management\Model\ValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSocialProvidersWithHttpInfo($realm, $sort = null, $filterKey = null, $filterDriver = null, $filterEnabled = null, $page = null, $perPage = null, string $contentType = self::contentTypes['listSocialProviders'][0])
    {
        $request = $this->listSocialProvidersRequest($realm, $sort, $filterKey, $filterDriver, $filterEnabled, $page, $perPage, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderCollection',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Management\Model\SocialProviderCollection',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderCollection',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'listSocialProviders'
     *
     * @param  string $realm The realm slug (required)
     * @param  string[]|null $sort Available sorts are &#x60;key&#x60;, &#x60;driver&#x60;, &#x60;created_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-key&#x60;. (optional)
     * @param  string[]|null $filterKey Filter by &#x60;key&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDriver Filter by &#x60;driver&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterEnabled Filter by &#x60;enabled&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  int|null $page The page number to retrieve. (optional)
     * @param  int|null $perPage The number of items to retrieve per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSocialProviders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listSocialProvidersRequest($realm, $sort = null, $filterKey = null, $filterDriver = null, $filterEnabled = null, $page = null, $perPage = null, string $contentType = self::contentTypes['listSocialProviders'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling listSocialProviders'
            );
        }





        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling SocialProvidersApi.listSocialProviders, must be bigger than or equal to 1.');
        }
        
        if ($perPage !== null && $perPage > 100) {
            throw new \InvalidArgumentException('invalid value for "$perPage" when calling SocialProvidersApi.listSocialProviders, must be smaller than or equal to 100.');
        }
        if ($perPage !== null && $perPage < 1) {
            throw new \InvalidArgumentException('invalid value for "$perPage" when calling SocialProvidersApi.listSocialProviders, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/v1/realms/{realm}/social-providers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filterKey,
            'filter[key]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filterDriver,
            'filter[driver]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filterEnabled,
            'filter[enabled]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $perPage,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchSocialProvider
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider socialProvider (required)
     * @param  \Lock\Client\OpenApi\Management\Model\UpdateSocialProviderData|null $updateSocialProviderData updateSocialProviderData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\ValidationError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError
     */
    public function patchSocialProvider($realm, $socialProvider, $updateSocialProviderData = null, string $contentType = self::contentTypes['patchSocialProvider'][0])
    {
        list($response) = $this->patchSocialProviderWithHttpInfo($realm, $socialProvider, $updateSocialProviderData, $contentType);
        return $response;
    }

    /**
     * Operation patchSocialProviderWithHttpInfo
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  \Lock\Client\OpenApi\Management\Model\UpdateSocialProviderData|null $updateSocialProviderData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\ValidationError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchSocialProviderWithHttpInfo($realm, $socialProvider, $updateSocialProviderData = null, string $contentType = self::contentTypes['patchSocialProvider'][0])
    {
        $request = $this->patchSocialProviderRequest($realm, $socialProvider, $updateSocialProviderData, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'patchSocialProvider'
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  \Lock\Client\OpenApi\Management\Model\UpdateSocialProviderData|null $updateSocialProviderData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchSocialProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchSocialProviderRequest($realm, $socialProvider, $updateSocialProviderData = null, string $contentType = self::contentTypes['patchSocialProvider'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling patchSocialProvider'
            );
        }

        // verify the required parameter 'socialProvider' is set
        if ($socialProvider === null || (is_array($socialProvider) && count($socialProvider) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $socialProvider when calling patchSocialProvider'
            );
        }



        $resourcePath = '/v1/realms/{realm}/social-providers/{social_provider}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }
        // path params
        if ($socialProvider !== null) {
            $resourcePath = str_replace(
                '{social_provider}',
                ObjectSerializer::toPathValue($socialProvider),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateSocialProviderData)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($updateSocialProviderData), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $updateSocialProviderData;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSocialProvider
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider socialProvider (required)
     * @param  \Lock\Client\OpenApi\Management\Model\UpdateSocialProviderData|null $updateSocialProviderData updateSocialProviderData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\ValidationError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError
     */
    public function updateSocialProvider($realm, $socialProvider, $updateSocialProviderData = null, string $contentType = self::contentTypes['updateSocialProvider'][0])
    {
        list($response) = $this->updateSocialProviderWithHttpInfo($realm, $socialProvider, $updateSocialProviderData, $contentType);
        return $response;
    }

    /**
     * Operation updateSocialProviderWithHttpInfo
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  \Lock\Client\OpenApi\Management\Model\UpdateSocialProviderData|null $updateSocialProviderData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSocialProvider'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Management\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Management\Model\SocialProviderResponse|\Lock\Client\OpenApi\Management\Model\NotFoundError|\Lock\Client\OpenApi\Management\Model\ValidationError|\Lock\Client\OpenApi\Management\Model\AuthenticationError|\Lock\Client\OpenApi\Management\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSocialProviderWithHttpInfo($realm, $socialProvider, $updateSocialProviderData = null, string $contentType = self::contentTypes['updateSocialProvider'][0])
    {
        $request = $this->updateSocialProviderRequest($realm, $socialProvider, $updateSocialProviderData, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\SocialProviderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Management\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'updateSocialProvider'
     *
     * @param  string $realm The realm slug (required)
     * @param  string $socialProvider (required)
     * @param  \Lock\Client\OpenApi\Management\Model\UpdateSocialProviderData|null $updateSocialProviderData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSocialProvider'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateSocialProviderRequest($realm, $socialProvider, $updateSocialProviderData = null, string $contentType = self::contentTypes['updateSocialProvider'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling updateSocialProvider'
            );
        }

        // verify the required parameter 'socialProvider' is set
        if ($socialProvider === null || (is_array($socialProvider) && count($socialProvider) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $socialProvider when calling updateSocialProvider'
            );
        }



        $resourcePath = '/v1/realms/{realm}/social-providers/{social_provider}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }
        // path params
        if ($socialProvider !== null) {
            $resourcePath = str_replace(
                '{social_provider}',
                ObjectSerializer::toPathValue($socialProvider),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateSocialProviderData)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($updateSocialProviderData), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $updateSocialProviderData;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
