<?php
/**
 * ClientData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\OpenApi\Management\Model;

use \ArrayAccess;
use \Lock\Client\OpenApi\Management\ObjectSerializer;

/**
 * ClientData Class Doc Comment
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClientData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public static function allowsAdditionalProperties(): bool
    {
        return false;
    }

    /** @return array<string, mixed> */
    public function getAdditionalProperties(): array
    {
        return self::allowsAdditionalProperties() ? array_diff_key($this->container, self::$openAPITypes) : [];
    }

    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ClientData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'clientId' => 'string',
        'realm' => 'string',
        'name' => 'string',
        'tokenEndpointAuthMethod' => '\Lock\Client\OpenApi\Management\Model\TokenEndpointAuthMethod',
        'confidential' => 'bool',
        'grantTypes' => 'string[]',
        'redirectUris' => 'string[]',
        'postLogoutRedirectUris' => 'string[]',
        'consentRequired' => 'bool',
        'backchannelLogoutUri' => 'string',
        'scopes' => 'string[]',
        'revoked' => 'bool',
        'revokedAt' => 'string',
        'createdAt' => 'string',
        'updatedAt' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'clientId' => null,
        'realm' => null,
        'name' => null,
        'tokenEndpointAuthMethod' => null,
        'confidential' => null,
        'grantTypes' => null,
        'redirectUris' => null,
        'postLogoutRedirectUris' => null,
        'consentRequired' => null,
        'backchannelLogoutUri' => null,
        'scopes' => null,
        'revoked' => null,
        'revokedAt' => null,
        'createdAt' => null,
        'updatedAt' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'clientId' => false,
        'realm' => false,
        'name' => false,
        'tokenEndpointAuthMethod' => false,
        'confidential' => false,
        'grantTypes' => false,
        'redirectUris' => false,
        'postLogoutRedirectUris' => false,
        'consentRequired' => false,
        'backchannelLogoutUri' => true,
        'scopes' => false,
        'revoked' => false,
        'revokedAt' => true,
        'createdAt' => true,
        'updatedAt' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'clientId' => 'client_id',
        'realm' => 'realm',
        'name' => 'name',
        'tokenEndpointAuthMethod' => 'token_endpoint_auth_method',
        'confidential' => 'confidential',
        'grantTypes' => 'grant_types',
        'redirectUris' => 'redirect_uris',
        'postLogoutRedirectUris' => 'post_logout_redirect_uris',
        'consentRequired' => 'consent_required',
        'backchannelLogoutUri' => 'backchannel_logout_uri',
        'scopes' => 'scopes',
        'revoked' => 'revoked',
        'revokedAt' => 'revoked_at',
        'createdAt' => 'created_at',
        'updatedAt' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'clientId' => 'setClientId',
        'realm' => 'setRealm',
        'name' => 'setName',
        'tokenEndpointAuthMethod' => 'setTokenEndpointAuthMethod',
        'confidential' => 'setConfidential',
        'grantTypes' => 'setGrantTypes',
        'redirectUris' => 'setRedirectUris',
        'postLogoutRedirectUris' => 'setPostLogoutRedirectUris',
        'consentRequired' => 'setConsentRequired',
        'backchannelLogoutUri' => 'setBackchannelLogoutUri',
        'scopes' => 'setScopes',
        'revoked' => 'setRevoked',
        'revokedAt' => 'setRevokedAt',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'clientId' => 'getClientId',
        'realm' => 'getRealm',
        'name' => 'getName',
        'tokenEndpointAuthMethod' => 'getTokenEndpointAuthMethod',
        'confidential' => 'getConfidential',
        'grantTypes' => 'getGrantTypes',
        'redirectUris' => 'getRedirectUris',
        'postLogoutRedirectUris' => 'getPostLogoutRedirectUris',
        'consentRequired' => 'getConsentRequired',
        'backchannelLogoutUri' => 'getBackchannelLogoutUri',
        'scopes' => 'getScopes',
        'revoked' => 'getRevoked',
        'revokedAt' => 'getRevokedAt',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clientId', $data ?? [], null);
        $this->setIfExists('realm', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('tokenEndpointAuthMethod', $data ?? [], null);
        $this->setIfExists('confidential', $data ?? [], null);
        $this->setIfExists('grantTypes', $data ?? [], null);
        $this->setIfExists('redirectUris', $data ?? [], null);
        $this->setIfExists('postLogoutRedirectUris', $data ?? [], null);
        $this->setIfExists('consentRequired', $data ?? [], null);
        $this->setIfExists('backchannelLogoutUri', $data ?? [], null);
        $this->setIfExists('scopes', $data ?? [], null);
        $this->setIfExists('revoked', $data ?? [], null);
        $this->setIfExists('revokedAt', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['clientId'] === null) {
            $invalidProperties[] = "'clientId' can't be null";
        }
        if ($this->container['clientId'] !== null && !is_string($this->container['clientId'])) {
            $invalidProperties[] = "'clientId' must be a string";
        } else {
        
        }
        
        if ($this->container['realm'] === null) {
            $invalidProperties[] = "'realm' can't be null";
        }
        if ($this->container['realm'] !== null && !is_string($this->container['realm'])) {
            $invalidProperties[] = "'realm' must be a string";
        } else {
        
        }
        
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['name'] !== null && !is_string($this->container['name'])) {
            $invalidProperties[] = "'name' must be a string";
        } else {
        
        }
        
        if ($this->container['tokenEndpointAuthMethod'] === null) {
            $invalidProperties[] = "'tokenEndpointAuthMethod' can't be null";
        }
        
        if ($this->container['confidential'] === null) {
            $invalidProperties[] = "'confidential' can't be null";
        }
        
        if ($this->container['grantTypes'] === null) {
            $invalidProperties[] = "'grantTypes' can't be null";
        }
        if ((count($this->container['grantTypes']) < 1)) {
            $invalidProperties[] = "invalid value for 'grantTypes', number of items must be greater than or equal to 1.";
        }

        
        if ($this->container['redirectUris'] === null) {
            $invalidProperties[] = "'redirectUris' can't be null";
        }
        if ((count($this->container['redirectUris']) < 1)) {
            $invalidProperties[] = "invalid value for 'redirectUris', number of items must be greater than or equal to 1.";
        }

        
        if ($this->container['postLogoutRedirectUris'] === null) {
            $invalidProperties[] = "'postLogoutRedirectUris' can't be null";
        }
        if ((count($this->container['postLogoutRedirectUris']) < 1)) {
            $invalidProperties[] = "invalid value for 'postLogoutRedirectUris', number of items must be greater than or equal to 1.";
        }

        
        if ($this->container['consentRequired'] === null) {
            $invalidProperties[] = "'consentRequired' can't be null";
        }
        
        if ($this->container['backchannelLogoutUri'] !== null && !is_string($this->container['backchannelLogoutUri'])) {
            $invalidProperties[] = "'backchannelLogoutUri' must be a string";
        } else {
        
        }
        
        if ($this->container['scopes'] === null) {
            $invalidProperties[] = "'scopes' can't be null";
        }
        if ((count($this->container['scopes']) < 1)) {
            $invalidProperties[] = "invalid value for 'scopes', number of items must be greater than or equal to 1.";
        }

        
        if ($this->container['revoked'] === null) {
            $invalidProperties[] = "'revoked' can't be null";
        }
        
        if ($this->container['revokedAt'] !== null && !is_string($this->container['revokedAt'])) {
            $invalidProperties[] = "'revokedAt' must be a string";
        } else {
        
        }
        
        if ($this->container['createdAt'] !== null && !is_string($this->container['createdAt'])) {
            $invalidProperties[] = "'createdAt' must be a string";
        } else {
        
        }
        
        if ($this->container['updatedAt'] !== null && !is_string($this->container['updatedAt'])) {
            $invalidProperties[] = "'updatedAt' must be a string";
        } else {
        
        }
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clientId
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string $clientId The identifier a relying party authenticates with, and its path in this API.
     *
     * @return self
     */
    public function setClientId($clientId)
    {
        if (is_null($clientId)) {
            throw new \InvalidArgumentException('non-nullable clientId cannot be null');
        }
        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets realm
     *
     * @return string
     */
    public function getRealm()
    {
        return $this->container['realm'];
    }

    /**
     * Sets realm
     *
     * @param string $realm The slug of the realm the client belongs to.
     *
     * @return self
     */
    public function setRealm($realm)
    {
        if (is_null($realm)) {
            throw new \InvalidArgumentException('non-nullable realm cannot be null');
        }
        $this->container['realm'] = $realm;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Human readable name, shown to the identity on the consent screen.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets tokenEndpointAuthMethod
     *
     * @return \Lock\Client\OpenApi\Management\Model\TokenEndpointAuthMethod
     */
    public function getTokenEndpointAuthMethod()
    {
        return $this->container['tokenEndpointAuthMethod'];
    }

    /**
     * Sets tokenEndpointAuthMethod
     *
     * @param \Lock\Client\OpenApi\Management\Model\TokenEndpointAuthMethod $tokenEndpointAuthMethod How the client authenticates at the token endpoint.
     *
     * @return self
     */
    public function setTokenEndpointAuthMethod($tokenEndpointAuthMethod)
    {
        if (is_null($tokenEndpointAuthMethod)) {
            throw new \InvalidArgumentException('non-nullable tokenEndpointAuthMethod cannot be null');
        }
        $this->container['tokenEndpointAuthMethod'] = $tokenEndpointAuthMethod;

        return $this;
    }

    /**
     * Gets confidential
     *
     * @return bool
     */
    public function getConfidential()
    {
        return $this->container['confidential'];
    }

    /**
     * Sets confidential
     *
     * @param bool $confidential Whether the client holds a secret.
     *
     * @return self
     */
    public function setConfidential($confidential)
    {
        if (is_null($confidential)) {
            throw new \InvalidArgumentException('non-nullable confidential cannot be null');
        }
        $this->container['confidential'] = $confidential;

        return $this;
    }

    /**
     * Gets grantTypes
     *
     * @return string[]
     */
    public function getGrantTypes()
    {
        return $this->container['grantTypes'];
    }

    /**
     * Sets grantTypes
     *
     * @param string[] $grantTypes The grants the client may use.
     *
     * @return self
     */
    public function setGrantTypes($grantTypes)
    {
        if (is_null($grantTypes)) {
            throw new \InvalidArgumentException('non-nullable grantTypes cannot be null');
        }

        if ((count($grantTypes) < 1)) {
            throw new \InvalidArgumentException('invalid length for $grantTypes when calling ClientData., number of items must be greater than or equal to 1.');
        }
        $this->container['grantTypes'] = $grantTypes;

        return $this;
    }

    /**
     * Gets redirectUris
     *
     * @return string[]
     */
    public function getRedirectUris()
    {
        return $this->container['redirectUris'];
    }

    /**
     * Sets redirectUris
     *
     * @param string[] $redirectUris Where an authorization response may be sent back to.
     *
     * @return self
     */
    public function setRedirectUris($redirectUris)
    {
        if (is_null($redirectUris)) {
            throw new \InvalidArgumentException('non-nullable redirectUris cannot be null');
        }

        if ((count($redirectUris) < 1)) {
            throw new \InvalidArgumentException('invalid length for $redirectUris when calling ClientData., number of items must be greater than or equal to 1.');
        }
        $this->container['redirectUris'] = $redirectUris;

        return $this;
    }

    /**
     * Gets postLogoutRedirectUris
     *
     * @return string[]
     */
    public function getPostLogoutRedirectUris()
    {
        return $this->container['postLogoutRedirectUris'];
    }

    /**
     * Sets postLogoutRedirectUris
     *
     * @param string[] $postLogoutRedirectUris Where an end-session request may return to.
     *
     * @return self
     */
    public function setPostLogoutRedirectUris($postLogoutRedirectUris)
    {
        if (is_null($postLogoutRedirectUris)) {
            throw new \InvalidArgumentException('non-nullable postLogoutRedirectUris cannot be null');
        }

        if ((count($postLogoutRedirectUris) < 1)) {
            throw new \InvalidArgumentException('invalid length for $postLogoutRedirectUris when calling ClientData., number of items must be greater than or equal to 1.');
        }
        $this->container['postLogoutRedirectUris'] = $postLogoutRedirectUris;

        return $this;
    }

    /**
     * Gets consentRequired
     *
     * @return bool
     */
    public function getConsentRequired()
    {
        return $this->container['consentRequired'];
    }

    /**
     * Sets consentRequired
     *
     * @param bool $consentRequired Whether the identity is asked to consent before the client is granted its scopes.
     *
     * @return self
     */
    public function setConsentRequired($consentRequired)
    {
        if (is_null($consentRequired)) {
            throw new \InvalidArgumentException('non-nullable consentRequired cannot be null');
        }
        $this->container['consentRequired'] = $consentRequired;

        return $this;
    }

    /**
     * Gets backchannelLogoutUri
     *
     * @return string|null
     */
    public function getBackchannelLogoutUri()
    {
        return $this->container['backchannelLogoutUri'];
    }

    /**
     * Sets backchannelLogoutUri
     *
     * @param string|null $backchannelLogoutUri Where a back-channel logout token is delivered.
     *
     * @return self
     */
    public function setBackchannelLogoutUri($backchannelLogoutUri)
    {
        if (is_null($backchannelLogoutUri)) {
            array_push($this->openAPINullablesSetToNull, 'backchannelLogoutUri');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('backchannelLogoutUri', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['backchannelLogoutUri'] = $backchannelLogoutUri;

        return $this;
    }

    /**
     * Gets scopes
     *
     * @return string[]
     */
    public function getScopes()
    {
        return $this->container['scopes'];
    }

    /**
     * Sets scopes
     *
     * @param string[] $scopes The scopes the client is granted, from the realm’s client policy.
     *
     * @return self
     */
    public function setScopes($scopes)
    {
        if (is_null($scopes)) {
            throw new \InvalidArgumentException('non-nullable scopes cannot be null');
        }

        if ((count($scopes) < 1)) {
            throw new \InvalidArgumentException('invalid length for $scopes when calling ClientData., number of items must be greater than or equal to 1.');
        }
        $this->container['scopes'] = $scopes;

        return $this;
    }

    /**
     * Gets revoked
     *
     * @return bool
     */
    public function getRevoked()
    {
        return $this->container['revoked'];
    }

    /**
     * Sets revoked
     *
     * @param bool $revoked Whether the client is blocked from obtaining tokens.
     *
     * @return self
     */
    public function setRevoked($revoked)
    {
        if (is_null($revoked)) {
            throw new \InvalidArgumentException('non-nullable revoked cannot be null');
        }
        $this->container['revoked'] = $revoked;

        return $this;
    }

    /**
     * Gets revokedAt
     *
     * @return string|null
     */
    public function getRevokedAt()
    {
        return $this->container['revokedAt'];
    }

    /**
     * Sets revokedAt
     *
     * @param string|null $revokedAt When the client was blocked, if it is.
     *
     * @return self
     */
    public function setRevokedAt($revokedAt)
    {
        if (is_null($revokedAt)) {
            array_push($this->openAPINullablesSetToNull, 'revokedAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('revokedAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['revokedAt'] = $revokedAt;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param string|null $createdAt When the client was created.
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            array_push($this->openAPINullablesSetToNull, 'createdAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('createdAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param string|null $updatedAt When the client was last changed.
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            array_push($this->openAPINullablesSetToNull, 'updatedAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updatedAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


