<?php
/**
 * RealmDomainStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Admin
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\OpenApi\Admin\Model;
use \Lock\Client\OpenApi\Admin\ObjectSerializer;

/**
 * RealmDomainStatus Class Doc Comment
 *
 * @category Class
 * @description What the last domain check found. &#x60;Unreachable&#x60; means no HTTP answer at all (DNS, connection, TLS); &#x60;Misrouted&#x60; means something answered, but not this Lock instance.
 * @package  Lock\Client\OpenApi\Admin
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RealmDomainStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const VERIFIED = 'verified';

    public const UNREACHABLE = 'unreachable';

    public const MISROUTED = 'misrouted';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::VERIFIED,
            self::UNREACHABLE,
            self::MISROUTED
        ];
    }
}


