<?php
/**
 * RealmData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\Management\Model;

use \ArrayAccess;
use \Lock\Client\Management\ObjectSerializer;

/**
 * RealmData Class Doc Comment
 *
 * @category Class
 * @package  Lock\Client\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RealmData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public static function allowsAdditionalProperties(): bool
    {
        return false;
    }

    /** @return array<string, mixed> */
    public function getAdditionalProperties(): array
    {
        return self::allowsAdditionalProperties() ? array_diff_key($this->container, self::$openAPITypes) : [];
    }

    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RealmData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'slug' => 'string',
        'name' => 'string',
        'host' => 'string',
        'issuer' => 'string',
        'domain' => 'string',
        'domainStatus' => '\Lock\Client\Management\Model\RealmDomainStatus',
        'domainCheckedAt' => 'string',
        'domainCheckError' => 'string',
        'master' => 'bool',
        'settings' => '\Lock\Client\Management\Model\RealmSettings',
        'createdAt' => 'string',
        'updatedAt' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'slug' => null,
        'name' => null,
        'host' => null,
        'issuer' => null,
        'domain' => null,
        'domainStatus' => null,
        'domainCheckedAt' => null,
        'domainCheckError' => null,
        'master' => null,
        'settings' => null,
        'createdAt' => null,
        'updatedAt' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'slug' => false,
        'name' => false,
        'host' => false,
        'issuer' => false,
        'domain' => true,
        'domainStatus' => false,
        'domainCheckedAt' => true,
        'domainCheckError' => true,
        'master' => false,
        'settings' => false,
        'createdAt' => true,
        'updatedAt' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'slug' => 'slug',
        'name' => 'name',
        'host' => 'host',
        'issuer' => 'issuer',
        'domain' => 'domain',
        'domainStatus' => 'domain_status',
        'domainCheckedAt' => 'domain_checked_at',
        'domainCheckError' => 'domain_check_error',
        'master' => 'master',
        'settings' => 'settings',
        'createdAt' => 'created_at',
        'updatedAt' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'slug' => 'setSlug',
        'name' => 'setName',
        'host' => 'setHost',
        'issuer' => 'setIssuer',
        'domain' => 'setDomain',
        'domainStatus' => 'setDomainStatus',
        'domainCheckedAt' => 'setDomainCheckedAt',
        'domainCheckError' => 'setDomainCheckError',
        'master' => 'setMaster',
        'settings' => 'setSettings',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'slug' => 'getSlug',
        'name' => 'getName',
        'host' => 'getHost',
        'issuer' => 'getIssuer',
        'domain' => 'getDomain',
        'domainStatus' => 'getDomainStatus',
        'domainCheckedAt' => 'getDomainCheckedAt',
        'domainCheckError' => 'getDomainCheckError',
        'master' => 'getMaster',
        'settings' => 'getSettings',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('issuer', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('domainStatus', $data ?? [], null);
        $this->setIfExists('domainCheckedAt', $data ?? [], null);
        $this->setIfExists('domainCheckError', $data ?? [], null);
        $this->setIfExists('master', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['slug'] === null) {
            $invalidProperties[] = "'slug' can't be null";
        }
        if ($this->container['slug'] !== null && !is_string($this->container['slug'])) {
            $invalidProperties[] = "'slug' must be a string";
        } else {
        
        }
        
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['name'] !== null && !is_string($this->container['name'])) {
            $invalidProperties[] = "'name' must be a string";
        } else {
        
        }
        
        if ($this->container['host'] === null) {
            $invalidProperties[] = "'host' can't be null";
        }
        if ($this->container['host'] !== null && !is_string($this->container['host'])) {
            $invalidProperties[] = "'host' must be a string";
        } else {
        
        }
        
        if ($this->container['issuer'] === null) {
            $invalidProperties[] = "'issuer' can't be null";
        }
        if ($this->container['issuer'] !== null && !is_string($this->container['issuer'])) {
            $invalidProperties[] = "'issuer' must be a string";
        } else {
        
        }
        
        if ($this->container['domain'] !== null && !is_string($this->container['domain'])) {
            $invalidProperties[] = "'domain' must be a string";
        } else {
        
        }
        
        if ($this->container['domainStatus'] === null) {
            $invalidProperties[] = "'domainStatus' can't be null";
        }
        
        if ($this->container['domainCheckedAt'] !== null && !is_string($this->container['domainCheckedAt'])) {
            $invalidProperties[] = "'domainCheckedAt' must be a string";
        } else {
        
        }
        
        if ($this->container['domainCheckError'] !== null && !is_string($this->container['domainCheckError'])) {
            $invalidProperties[] = "'domainCheckError' must be a string";
        } else {
        
        }
        
        if ($this->container['master'] === null) {
            $invalidProperties[] = "'master' can't be null";
        }
        
        if ($this->container['settings'] === null) {
            $invalidProperties[] = "'settings' can't be null";
        }
        
        if ($this->container['createdAt'] !== null && !is_string($this->container['createdAt'])) {
            $invalidProperties[] = "'createdAt' must be a string";
        } else {
        
        }
        
        if ($this->container['updatedAt'] !== null && !is_string($this->container['updatedAt'])) {
            $invalidProperties[] = "'updatedAt' must be a string";
        } else {
        
        }
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug Stable identifier of the realm, and its path in this API.
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Human readable name shown to its users.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string $host The host the realm is served from.
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            throw new \InvalidArgumentException('non-nullable host cannot be null');
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets issuer
     *
     * @return string
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     *
     * @param string $issuer The realm’s OIDC issuer, the `iss` of every token it mints.
     *
     * @return self
     */
    public function setIssuer($issuer)
    {
        if (is_null($issuer)) {
            throw new \InvalidArgumentException('non-nullable issuer cannot be null');
        }
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain The configured domain; null for the master realm, which follows APP_URL.
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            array_push($this->openAPINullablesSetToNull, 'domain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets domainStatus
     *
     * @return \Lock\Client\Management\Model\RealmDomainStatus
     */
    public function getDomainStatus()
    {
        return $this->container['domainStatus'];
    }

    /**
     * Sets domainStatus
     *
     * @param \Lock\Client\Management\Model\RealmDomainStatus $domainStatus Whether the configured domain was seen to reach this instance.
     *
     * @return self
     */
    public function setDomainStatus($domainStatus)
    {
        if (is_null($domainStatus)) {
            throw new \InvalidArgumentException('non-nullable domainStatus cannot be null');
        }
        $this->container['domainStatus'] = $domainStatus;

        return $this;
    }

    /**
     * Gets domainCheckedAt
     *
     * @return string|null
     */
    public function getDomainCheckedAt()
    {
        return $this->container['domainCheckedAt'];
    }

    /**
     * Sets domainCheckedAt
     *
     * @param string|null $domainCheckedAt When the domain was last checked.
     *
     * @return self
     */
    public function setDomainCheckedAt($domainCheckedAt)
    {
        if (is_null($domainCheckedAt)) {
            array_push($this->openAPINullablesSetToNull, 'domainCheckedAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domainCheckedAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domainCheckedAt'] = $domainCheckedAt;

        return $this;
    }

    /**
     * Gets domainCheckError
     *
     * @return string|null
     */
    public function getDomainCheckError()
    {
        return $this->container['domainCheckError'];
    }

    /**
     * Sets domainCheckError
     *
     * @param string|null $domainCheckError Why the last domain check failed, when it did.
     *
     * @return self
     */
    public function setDomainCheckError($domainCheckError)
    {
        if (is_null($domainCheckError)) {
            array_push($this->openAPINullablesSetToNull, 'domainCheckError');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domainCheckError', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domainCheckError'] = $domainCheckError;

        return $this;
    }

    /**
     * Gets master
     *
     * @return bool
     */
    public function getMaster()
    {
        return $this->container['master'];
    }

    /**
     * Sets master
     *
     * @param bool $master Whether this is the administration realm, which cannot be deleted or re-pointed.
     *
     * @return self
     */
    public function setMaster($master)
    {
        if (is_null($master)) {
            throw new \InvalidArgumentException('non-nullable master cannot be null');
        }
        $this->container['master'] = $master;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \Lock\Client\Management\Model\RealmSettings
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \Lock\Client\Management\Model\RealmSettings $settings The realm’s own policy.
     *
     * @return self
     */
    public function setSettings($settings)
    {
        if (is_null($settings)) {
            throw new \InvalidArgumentException('non-nullable settings cannot be null');
        }
        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param string|null $createdAt When the realm was created.
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            array_push($this->openAPINullablesSetToNull, 'createdAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('createdAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param string|null $updatedAt When the realm was last changed.
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            array_push($this->openAPINullablesSetToNull, 'updatedAt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updatedAt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


