<?php
/**
 * SocialProviderDriver
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\Management\Model;
use \Lock\Client\Management\ObjectSerializer;

/**
 * SocialProviderDriver Class Doc Comment
 *
 * @category Class
 * @description The brokering drivers use-lock/server&#39;s SocialProviderRegistry ships. Each one needs a different set of credentials, which is why the stored config is a map rather than columns.
 * @package  Lock\Client\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SocialProviderDriver
{
    /**
     * Possible values of this enum
     */
    public const GOOGLE = 'google';

    public const APPLE = 'apple';

    public const GITHUB = 'github';

    public const OIDC = 'oidc';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GOOGLE,
            self::APPLE,
            self::GITHUB,
            self::OIDC
        ];
    }
}


