<?php
/**
 * JsonWebKey
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\Oidc
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\Oidc\Model;

use \ArrayAccess;
use \Lock\Client\Oidc\ObjectSerializer;

/**
 * JsonWebKey Class Doc Comment
 *
 * @category Class
 * @package  Lock\Client\Oidc
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class JsonWebKey implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public static function allowsAdditionalProperties(): bool
    {
        return false;
    }

    /** @return array<string, mixed> */
    public function getAdditionalProperties(): array
    {
        return self::allowsAdditionalProperties() ? array_diff_key($this->container, self::$openAPITypes) : [];
    }

    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'JsonWebKey';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'kty' => 'string',
        'use' => 'string',
        'kid' => 'string',
        'alg' => 'string',
        'n' => 'string',
        'e' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'kty' => null,
        'use' => null,
        'kid' => null,
        'alg' => null,
        'n' => null,
        'e' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'kty' => false,
        'use' => false,
        'kid' => false,
        'alg' => false,
        'n' => false,
        'e' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kty' => 'kty',
        'use' => 'use',
        'kid' => 'kid',
        'alg' => 'alg',
        'n' => 'n',
        'e' => 'e'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kty' => 'setKty',
        'use' => 'setUse',
        'kid' => 'setKid',
        'alg' => 'setAlg',
        'n' => 'setN',
        'e' => 'setE'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kty' => 'getKty',
        'use' => 'getUse',
        'kid' => 'getKid',
        'alg' => 'getAlg',
        'n' => 'getN',
        'e' => 'getE'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const KTY_RSA = 'RSA';
    public const MODEL_USE_SIG = 'sig';
    public const ALG_RS256 = 'RS256';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKtyAllowableValues()
    {
        return [
            self::KTY_RSA,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUseAllowableValues()
    {
        return [
            self::MODEL_USE_SIG,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAlgAllowableValues()
    {
        return [
            self::ALG_RS256,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kty', $data ?? [], null);
        $this->setIfExists('use', $data ?? [], null);
        $this->setIfExists('kid', $data ?? [], null);
        $this->setIfExists('alg', $data ?? [], null);
        $this->setIfExists('n', $data ?? [], null);
        $this->setIfExists('e', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['kty'] === null) {
            $invalidProperties[] = "'kty' can't be null";
        }
        if ($this->container['kty'] !== null && !is_string($this->container['kty'])) {
            $invalidProperties[] = "'kty' must be a string";
        } else {
        $allowedValues = $this->getKtyAllowableValues();
        if (!is_null($this->container['kty']) && !in_array($this->container['kty'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kty', must be one of '%s'",
                $this->container['kty'],
                implode("', '", $allowedValues)
            );
        }

        
        }
        
        if ($this->container['use'] === null) {
            $invalidProperties[] = "'use' can't be null";
        }
        if ($this->container['use'] !== null && !is_string($this->container['use'])) {
            $invalidProperties[] = "'use' must be a string";
        } else {
        $allowedValues = $this->getUseAllowableValues();
        if (!is_null($this->container['use']) && !in_array($this->container['use'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'use', must be one of '%s'",
                $this->container['use'],
                implode("', '", $allowedValues)
            );
        }

        
        }
        
        if ($this->container['kid'] === null) {
            $invalidProperties[] = "'kid' can't be null";
        }
        if ($this->container['kid'] !== null && !is_string($this->container['kid'])) {
            $invalidProperties[] = "'kid' must be a string";
        } else {
        
        }
        
        if ($this->container['alg'] === null) {
            $invalidProperties[] = "'alg' can't be null";
        }
        if ($this->container['alg'] !== null && !is_string($this->container['alg'])) {
            $invalidProperties[] = "'alg' must be a string";
        } else {
        $allowedValues = $this->getAlgAllowableValues();
        if (!is_null($this->container['alg']) && !in_array($this->container['alg'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'alg', must be one of '%s'",
                $this->container['alg'],
                implode("', '", $allowedValues)
            );
        }

        
        }
        
        if ($this->container['n'] === null) {
            $invalidProperties[] = "'n' can't be null";
        }
        if ($this->container['n'] !== null && !is_string($this->container['n'])) {
            $invalidProperties[] = "'n' must be a string";
        } else {
        
        }
        
        if ($this->container['e'] === null) {
            $invalidProperties[] = "'e' can't be null";
        }
        if ($this->container['e'] !== null && !is_string($this->container['e'])) {
            $invalidProperties[] = "'e' must be a string";
        } else {
        
        }
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kty
     *
     * @return string
     */
    public function getKty()
    {
        return $this->container['kty'];
    }

    /**
     * Sets kty
     *
     * @param string $kty kty
     *
     * @return self
     */
    public function setKty($kty)
    {
        if (is_null($kty)) {
            throw new \InvalidArgumentException('non-nullable kty cannot be null');
        }
        $allowedValues = $this->getKtyAllowableValues();
        if (!in_array($kty, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kty', must be one of '%s'",
                    $kty,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kty'] = $kty;

        return $this;
    }

    /**
     * Gets use
     *
     * @return string
     */
    public function getUse()
    {
        return $this->container['use'];
    }

    /**
     * Sets use
     *
     * @param string $use use
     *
     * @return self
     */
    public function setUse($use)
    {
        if (is_null($use)) {
            throw new \InvalidArgumentException('non-nullable use cannot be null');
        }
        $allowedValues = $this->getUseAllowableValues();
        if (!in_array($use, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'use', must be one of '%s'",
                    $use,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['use'] = $use;

        return $this;
    }

    /**
     * Gets kid
     *
     * @return string
     */
    public function getKid()
    {
        return $this->container['kid'];
    }

    /**
     * Sets kid
     *
     * @param string $kid kid
     *
     * @return self
     */
    public function setKid($kid)
    {
        if (is_null($kid)) {
            throw new \InvalidArgumentException('non-nullable kid cannot be null');
        }
        $this->container['kid'] = $kid;

        return $this;
    }

    /**
     * Gets alg
     *
     * @return string
     */
    public function getAlg()
    {
        return $this->container['alg'];
    }

    /**
     * Sets alg
     *
     * @param string $alg alg
     *
     * @return self
     */
    public function setAlg($alg)
    {
        if (is_null($alg)) {
            throw new \InvalidArgumentException('non-nullable alg cannot be null');
        }
        $allowedValues = $this->getAlgAllowableValues();
        if (!in_array($alg, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'alg', must be one of '%s'",
                    $alg,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['alg'] = $alg;

        return $this;
    }

    /**
     * Gets n
     *
     * @return string
     */
    public function getN()
    {
        return $this->container['n'];
    }

    /**
     * Sets n
     *
     * @param string $n Base64url-encoded RSA modulus.
     *
     * @return self
     */
    public function setN($n)
    {
        if (is_null($n)) {
            throw new \InvalidArgumentException('non-nullable n cannot be null');
        }
        $this->container['n'] = $n;

        return $this;
    }

    /**
     * Gets e
     *
     * @return string
     */
    public function getE()
    {
        return $this->container['e'];
    }

    /**
     * Sets e
     *
     * @param string $e Base64url-encoded RSA exponent.
     *
     * @return self
     */
    public function setE($e)
    {
        if (is_null($e)) {
            throw new \InvalidArgumentException('non-nullable e cannot be null');
        }
        $this->container['e'] = $e;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


