<?php
/**
 * AuthorizationApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\OpenApi\Auth\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Lock\Client\OpenApi\Auth\ApiException;
use Lock\Client\OpenApi\Auth\Configuration;
use Lock\Client\OpenApi\Auth\HeaderSelector;
use Lock\Client\OpenApi\Auth\ObjectSerializer;

/**
 * AuthorizationApi Class Doc Comment
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthorizationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'authorize' => [
            'application/json',
        ],
        'submitAuthorization' => [
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation authorize
     *
     * Authorize a client
     *
     * @param  string $clientId clientId (required)
     * @param  string $responseType responseType (required)
     * @param  string $codeChallenge codeChallenge (required)
     * @param  string $codeChallengeMethod codeChallengeMethod (required)
     * @param  string|null $redirectUri redirectUri (optional)
     * @param  string|null $scope scope (optional)
     * @param  string|null $state state (optional)
     * @param  string|string[]|null $resource resource (optional)
     * @param  string|null $nonce nonce (optional)
     * @param  string|null $prompt prompt (optional)
     * @param  int|null $maxAge maxAge (optional)
     * @param  string|null $acrValues acrValues (optional)
     * @param  string|null $idTokenHint idTokenHint (optional)
     * @param  string|null $responseMode responseMode (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorize'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string|\Lock\Client\OpenApi\Auth\Model\OAuthError
     */
    public function authorize($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri = null, $scope = null, $state = null, string|array|null $resource = null, $nonce = null, $prompt = null, $maxAge = null, $acrValues = null, $idTokenHint = null, $responseMode = null, string $contentType = self::contentTypes['authorize'][0])
    {
        list($response) = $this->authorizeWithHttpInfo($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri, $scope, $state, $resource, $nonce, $prompt, $maxAge, $acrValues, $idTokenHint, $responseMode, $contentType);
        return $response;
    }

    /**
     * Operation authorizeWithHttpInfo
     *
     * Authorize a client
     *
     * @param  string $clientId (required)
     * @param  string $responseType (required)
     * @param  string $codeChallenge (required)
     * @param  string $codeChallengeMethod (required)
     * @param  string|null $redirectUri (optional)
     * @param  string|null $scope (optional)
     * @param  string|null $state (optional)
     * @param  string|string[]|null $resource (optional)
     * @param  string|null $nonce (optional)
     * @param  string|null $prompt (optional)
     * @param  int|null $maxAge (optional)
     * @param  string|null $acrValues (optional)
     * @param  string|null $idTokenHint (optional)
     * @param  string|null $responseMode (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorize'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string|\Lock\Client\OpenApi\Auth\Model\OAuthError, HTTP status code, HTTP response headers (array of strings)
     */
    public function authorizeWithHttpInfo($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri = null, $scope = null, $state = null, string|array|null $resource = null, $nonce = null, $prompt = null, $maxAge = null, $acrValues = null, $idTokenHint = null, $responseMode = null, string $contentType = self::contentTypes['authorize'][0])
    {
        $request = $this->authorizeRequest($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri, $scope, $state, $resource, $nonce, $prompt, $maxAge, $acrValues, $idTokenHint, $responseMode, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Auth\Model\OAuthError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Auth\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'authorize'
     *
     * @param  string $clientId (required)
     * @param  string $responseType (required)
     * @param  string $codeChallenge (required)
     * @param  string $codeChallengeMethod (required)
     * @param  string|null $redirectUri (optional)
     * @param  string|null $scope (optional)
     * @param  string|null $state (optional)
     * @param  string|string[]|null $resource (optional)
     * @param  string|null $nonce (optional)
     * @param  string|null $prompt (optional)
     * @param  int|null $maxAge (optional)
     * @param  string|null $acrValues (optional)
     * @param  string|null $idTokenHint (optional)
     * @param  string|null $responseMode (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorize'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authorizeRequest($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri = null, $scope = null, $state = null, string|array|null $resource = null, $nonce = null, $prompt = null, $maxAge = null, $acrValues = null, $idTokenHint = null, $responseMode = null, string $contentType = self::contentTypes['authorize'][0])
    {

        // verify the required parameter 'clientId' is set
        if ($clientId === null || (is_array($clientId) && count($clientId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clientId when calling authorize'
            );
        }

        // verify the required parameter 'responseType' is set
        if ($responseType === null || (is_array($responseType) && count($responseType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $responseType when calling authorize'
            );
        }

        // verify the required parameter 'codeChallenge' is set
        if ($codeChallenge === null || (is_array($codeChallenge) && count($codeChallenge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $codeChallenge when calling authorize'
            );
        }

        // verify the required parameter 'codeChallengeMethod' is set
        if ($codeChallengeMethod === null || (is_array($codeChallengeMethod) && count($codeChallengeMethod) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $codeChallengeMethod when calling authorize'
            );
        }







        if ($maxAge !== null && $maxAge < 0) {
            throw new \InvalidArgumentException('invalid value for "$maxAge" when calling AuthorizationApi.authorize, must be bigger than or equal to 0.');
        }
        




        $resourcePath = '/oauth/authorize';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $clientId,
            'client_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $responseType,
            'response_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $redirectUri,
            'redirect_uri', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $scope,
            'scope', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $state,
            'state', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $resource,
            is_array($resource) ? 'resource[]' : 'resource', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $codeChallenge,
            'code_challenge', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $codeChallengeMethod,
            'code_challenge_method', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nonce,
            'nonce', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $prompt,
            'prompt', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $maxAge,
            'max_age', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $acrValues,
            'acr_values', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $idTokenHint,
            'id_token_hint', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $responseMode,
            'response_mode', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/html', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation submitAuthorization
     *
     * Authorize a client
     *
     * @param  string $clientId clientId (required)
     * @param  string $responseType responseType (required)
     * @param  string $codeChallenge Base64url-encoded SHA-256 digest of the PKCE verifier. (required)
     * @param  string $codeChallengeMethod codeChallengeMethod (required)
     * @param  string|null $redirectUri Registered callback. May be omitted only when the client has exactly one registered redirect URI. (optional)
     * @param  string|null $scope Space-delimited scopes; include openid for OpenID Connect. (optional)
     * @param  string|null $state Opaque client state echoed on the callback. (optional)
     * @param  string|string[]|null $resource Absolute protected-resource URI without a fragment, or an array of such URIs using resource[] fields. Authorization and client-credentials requests default to the realm audience. Code and refresh grants preserve the original audiences when omitted, or narrow them when supplied. (optional)
     * @param  string|null $nonce Nonce bound to the issued ID token. (optional)
     * @param  string|null $prompt Space-delimited none, login, consent or select_account. none must be used alone. (optional)
     * @param  int|null $maxAge Maximum acceptable age of authentication in seconds. (optional)
     * @param  string|null $acrValues Space-delimited requested authentication context values. (optional)
     * @param  string|null $idTokenHint idTokenHint (optional)
     * @param  string|null $responseMode responseMode (optional)
     * @param  string|null $token Browser CSRF token, alternatively sent using X-CSRF-TOKEN. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitAuthorization'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string|\Lock\Client\OpenApi\Auth\Model\OAuthError
     */
    public function submitAuthorization($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri = null, $scope = null, $state = null, string|array|null $resource = null, $nonce = null, $prompt = null, $maxAge = null, $acrValues = null, $idTokenHint = null, $responseMode = null, $token = null, string $contentType = self::contentTypes['submitAuthorization'][0])
    {
        list($response) = $this->submitAuthorizationWithHttpInfo($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri, $scope, $state, $resource, $nonce, $prompt, $maxAge, $acrValues, $idTokenHint, $responseMode, $token, $contentType);
        return $response;
    }

    /**
     * Operation submitAuthorizationWithHttpInfo
     *
     * Authorize a client
     *
     * @param  string $clientId (required)
     * @param  string $responseType (required)
     * @param  string $codeChallenge Base64url-encoded SHA-256 digest of the PKCE verifier. (required)
     * @param  string $codeChallengeMethod (required)
     * @param  string|null $redirectUri Registered callback. May be omitted only when the client has exactly one registered redirect URI. (optional)
     * @param  string|null $scope Space-delimited scopes; include openid for OpenID Connect. (optional)
     * @param  string|null $state Opaque client state echoed on the callback. (optional)
     * @param  string|string[]|null $resource Absolute protected-resource URI without a fragment, or an array of such URIs using resource[] fields. Authorization and client-credentials requests default to the realm audience. Code and refresh grants preserve the original audiences when omitted, or narrow them when supplied. (optional)
     * @param  string|null $nonce Nonce bound to the issued ID token. (optional)
     * @param  string|null $prompt Space-delimited none, login, consent or select_account. none must be used alone. (optional)
     * @param  int|null $maxAge Maximum acceptable age of authentication in seconds. (optional)
     * @param  string|null $acrValues Space-delimited requested authentication context values. (optional)
     * @param  string|null $idTokenHint (optional)
     * @param  string|null $responseMode (optional)
     * @param  string|null $token Browser CSRF token, alternatively sent using X-CSRF-TOKEN. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitAuthorization'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string|\Lock\Client\OpenApi\Auth\Model\OAuthError, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitAuthorizationWithHttpInfo($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri = null, $scope = null, $state = null, string|array|null $resource = null, $nonce = null, $prompt = null, $maxAge = null, $acrValues = null, $idTokenHint = null, $responseMode = null, $token = null, string $contentType = self::contentTypes['submitAuthorization'][0])
    {
        $request = $this->submitAuthorizationRequest($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri, $scope, $state, $resource, $nonce, $prompt, $maxAge, $acrValues, $idTokenHint, $responseMode, $token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Auth\Model\OAuthError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Auth\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'submitAuthorization'
     *
     * @param  string $clientId (required)
     * @param  string $responseType (required)
     * @param  string $codeChallenge Base64url-encoded SHA-256 digest of the PKCE verifier. (required)
     * @param  string $codeChallengeMethod (required)
     * @param  string|null $redirectUri Registered callback. May be omitted only when the client has exactly one registered redirect URI. (optional)
     * @param  string|null $scope Space-delimited scopes; include openid for OpenID Connect. (optional)
     * @param  string|null $state Opaque client state echoed on the callback. (optional)
     * @param  string|string[]|null $resource Absolute protected-resource URI without a fragment, or an array of such URIs using resource[] fields. Authorization and client-credentials requests default to the realm audience. Code and refresh grants preserve the original audiences when omitted, or narrow them when supplied. (optional)
     * @param  string|null $nonce Nonce bound to the issued ID token. (optional)
     * @param  string|null $prompt Space-delimited none, login, consent or select_account. none must be used alone. (optional)
     * @param  int|null $maxAge Maximum acceptable age of authentication in seconds. (optional)
     * @param  string|null $acrValues Space-delimited requested authentication context values. (optional)
     * @param  string|null $idTokenHint (optional)
     * @param  string|null $responseMode (optional)
     * @param  string|null $token Browser CSRF token, alternatively sent using X-CSRF-TOKEN. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitAuthorization'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function submitAuthorizationRequest($clientId, $responseType, $codeChallenge, $codeChallengeMethod, $redirectUri = null, $scope = null, $state = null, string|array|null $resource = null, $nonce = null, $prompt = null, $maxAge = null, $acrValues = null, $idTokenHint = null, $responseMode = null, $token = null, string $contentType = self::contentTypes['submitAuthorization'][0])
    {

        // verify the required parameter 'clientId' is set
        if ($clientId === null || (is_array($clientId) && count($clientId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clientId when calling submitAuthorization'
            );
        }

        // verify the required parameter 'responseType' is set
        if ($responseType === null || (is_array($responseType) && count($responseType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $responseType when calling submitAuthorization'
            );
        }

        // verify the required parameter 'codeChallenge' is set
        if ($codeChallenge === null || (is_array($codeChallenge) && count($codeChallenge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $codeChallenge when calling submitAuthorization'
            );
        }

        // verify the required parameter 'codeChallengeMethod' is set
        if ($codeChallengeMethod === null || (is_array($codeChallengeMethod) && count($codeChallengeMethod) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $codeChallengeMethod when calling submitAuthorization'
            );
        }







        if ($maxAge !== null && $maxAge < 0) {
            throw new \InvalidArgumentException('invalid value for "$maxAge" when calling AuthorizationApi.submitAuthorization, must be bigger than or equal to 0.');
        }
        





        $resourcePath = '/oauth/authorize';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new \Lock\Client\OpenApi\Auth\FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'client_id' => $clientId,
            'response_type' => $responseType,
            'redirect_uri' => $redirectUri,
            'scope' => $scope,
            'state' => $state,
            'resource' => $resource,
            'code_challenge' => $codeChallenge,
            'code_challenge_method' => $codeChallengeMethod,
            'nonce' => $nonce,
            'prompt' => $prompt,
            'max_age' => $maxAge,
            'acr_values' => $acrValues,
            'id_token_hint' => $idTokenHint,
            'response_mode' => $responseMode,
            '_token' => $token,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['text/html', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
