<?php
/**
 * RealmsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Admin
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\OpenApi\Admin\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Lock\Client\OpenApi\Admin\ApiException;
use Lock\Client\OpenApi\Admin\Configuration;
use Lock\Client\OpenApi\Admin\HeaderSelector;
use Lock\Client\OpenApi\Admin\ObjectSerializer;

/**
 * RealmsApi Class Doc Comment
 *
 * @category Class
 * @package  Lock\Client\OpenApi\Admin
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RealmsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createRealm' => [
            'application/json',
        ],
        'deleteRealm' => [
            'application/json',
        ],
        'getRealm' => [
            'application/json',
        ],
        'listRealms' => [
            'application/json',
        ],
        'patchRealm' => [
            'application/json',
        ],
        'updateRealm' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createRealm
     *
     * Create a realm
     *
     * @param  \Lock\Client\OpenApi\Admin\Model\CreateRealmData $createRealmData createRealmData (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\ValidationError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError
     */
    public function createRealm($createRealmData, string $contentType = self::contentTypes['createRealm'][0])
    {
        list($response) = $this->createRealmWithHttpInfo($createRealmData, $contentType);
        return $response;
    }

    /**
     * Operation createRealmWithHttpInfo
     *
     * Create a realm
     *
     * @param  \Lock\Client\OpenApi\Admin\Model\CreateRealmData $createRealmData (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\ValidationError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createRealmWithHttpInfo($createRealmData, string $contentType = self::contentTypes['createRealm'][0])
    {
        $request = $this->createRealmRequest($createRealmData, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'createRealm'
     *
     * @param  \Lock\Client\OpenApi\Admin\Model\CreateRealmData $createRealmData (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRealm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createRealmRequest($createRealmData, string $contentType = self::contentTypes['createRealm'][0])
    {

        // verify the required parameter 'createRealmData' is set
        if ($createRealmData === null || (is_array($createRealmData) && count($createRealmData) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $createRealmData when calling createRealm'
            );
        }


        $resourcePath = '/v1/realms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createRealmData)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($createRealmData), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $createRealmData;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteRealm
     *
     * Delete a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteRealm($realm, string $contentType = self::contentTypes['deleteRealm'][0])
    {
        $this->deleteRealmWithHttpInfo($realm, $contentType);
    }

    /**
     * Operation deleteRealmWithHttpInfo
     *
     * Delete a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteRealmWithHttpInfo($realm, string $contentType = self::contentTypes['deleteRealm'][0])
    {
        $request = $this->deleteRealmRequest($realm, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'deleteRealm'
     *
     * @param  string $realm The realm slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRealm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteRealmRequest($realm, string $contentType = self::contentTypes['deleteRealm'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling deleteRealm'
            );
        }


        $resourcePath = '/v1/realms/{realm}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRealm
     *
     * Show a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\NotFoundError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError
     */
    public function getRealm($realm, string $contentType = self::contentTypes['getRealm'][0])
    {
        list($response) = $this->getRealmWithHttpInfo($realm, $contentType);
        return $response;
    }

    /**
     * Operation getRealmWithHttpInfo
     *
     * Show a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\NotFoundError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRealmWithHttpInfo($realm, string $contentType = self::contentTypes['getRealm'][0])
    {
        $request = $this->getRealmRequest($realm, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'getRealm'
     *
     * @param  string $realm The realm slug (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRealm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRealmRequest($realm, string $contentType = self::contentTypes['getRealm'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling getRealm'
            );
        }


        $resourcePath = '/v1/realms/{realm}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listRealms
     *
     * List realms
     *
     * @param  string[]|null $sort Available sorts are &#x60;name&#x60;, &#x60;slug&#x60;, &#x60;created_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-name&#x60;. (optional)
     * @param  string[]|null $filterName Filter by &#x60;name&#x60;. Matches values containing the given text, case-insensitively. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterSlug Filter by &#x60;slug&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDomain Filter by &#x60;domain&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDomainStatus Filter by &#x60;domain_status&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  int|null $page The page number to retrieve. (optional)
     * @param  int|null $perPage The number of items to retrieve per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRealms'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Admin\Model\RealmCollection|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError|\Lock\Client\OpenApi\Admin\Model\ValidationError
     */
    public function listRealms($sort = null, $filterName = null, $filterSlug = null, $filterDomain = null, $filterDomainStatus = null, $page = null, $perPage = null, string $contentType = self::contentTypes['listRealms'][0])
    {
        list($response) = $this->listRealmsWithHttpInfo($sort, $filterName, $filterSlug, $filterDomain, $filterDomainStatus, $page, $perPage, $contentType);
        return $response;
    }

    /**
     * Operation listRealmsWithHttpInfo
     *
     * List realms
     *
     * @param  string[]|null $sort Available sorts are &#x60;name&#x60;, &#x60;slug&#x60;, &#x60;created_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-name&#x60;. (optional)
     * @param  string[]|null $filterName Filter by &#x60;name&#x60;. Matches values containing the given text, case-insensitively. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterSlug Filter by &#x60;slug&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDomain Filter by &#x60;domain&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDomainStatus Filter by &#x60;domain_status&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  int|null $page The page number to retrieve. (optional)
     * @param  int|null $perPage The number of items to retrieve per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRealms'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Admin\Model\RealmCollection|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError|\Lock\Client\OpenApi\Admin\Model\ValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listRealmsWithHttpInfo($sort = null, $filterName = null, $filterSlug = null, $filterDomain = null, $filterDomainStatus = null, $page = null, $perPage = null, string $contentType = self::contentTypes['listRealms'][0])
    {
        $request = $this->listRealmsRequest($sort, $filterName, $filterSlug, $filterDomain, $filterDomainStatus, $page, $perPage, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\RealmCollection',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Admin\Model\RealmCollection',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\RealmCollection',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'listRealms'
     *
     * @param  string[]|null $sort Available sorts are &#x60;name&#x60;, &#x60;slug&#x60;, &#x60;created_at&#x60;. You can sort by multiple options by separating them with a comma. To sort in descending order, use &#x60;-&#x60; sign in front of the sort, for example: &#x60;-name&#x60;. (optional)
     * @param  string[]|null $filterName Filter by &#x60;name&#x60;. Matches values containing the given text, case-insensitively. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterSlug Filter by &#x60;slug&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDomain Filter by &#x60;domain&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  string[]|null $filterDomainStatus Filter by &#x60;domain_status&#x60;. Matches the exact value. Separate multiple values with a comma; records matching any value qualify. (optional)
     * @param  int|null $page The page number to retrieve. (optional)
     * @param  int|null $perPage The number of items to retrieve per page. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRealms'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listRealmsRequest($sort = null, $filterName = null, $filterSlug = null, $filterDomain = null, $filterDomainStatus = null, $page = null, $perPage = null, string $contentType = self::contentTypes['listRealms'][0])
    {






        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling RealmsApi.listRealms, must be bigger than or equal to 1.');
        }
        
        if ($perPage !== null && $perPage > 100) {
            throw new \InvalidArgumentException('invalid value for "$perPage" when calling RealmsApi.listRealms, must be smaller than or equal to 100.');
        }
        if ($perPage !== null && $perPage < 1) {
            throw new \InvalidArgumentException('invalid value for "$perPage" when calling RealmsApi.listRealms, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/v1/realms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filterName,
            'filter[name]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filterSlug,
            'filter[slug]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filterDomain,
            'filter[domain]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filterDomainStatus,
            'filter[domain_status]', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $perPage,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchRealm
     *
     * Update a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Admin\Model\UpdateRealmData|null $updateRealmData updateRealmData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\NotFoundError|\Lock\Client\OpenApi\Admin\Model\ValidationError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError
     */
    public function patchRealm($realm, $updateRealmData = null, string $contentType = self::contentTypes['patchRealm'][0])
    {
        list($response) = $this->patchRealmWithHttpInfo($realm, $updateRealmData, $contentType);
        return $response;
    }

    /**
     * Operation patchRealmWithHttpInfo
     *
     * Update a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Admin\Model\UpdateRealmData|null $updateRealmData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\NotFoundError|\Lock\Client\OpenApi\Admin\Model\ValidationError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchRealmWithHttpInfo($realm, $updateRealmData = null, string $contentType = self::contentTypes['patchRealm'][0])
    {
        $request = $this->patchRealmRequest($realm, $updateRealmData, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'patchRealm'
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Admin\Model\UpdateRealmData|null $updateRealmData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchRealm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchRealmRequest($realm, $updateRealmData = null, string $contentType = self::contentTypes['patchRealm'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling patchRealm'
            );
        }



        $resourcePath = '/v1/realms/{realm}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateRealmData)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($updateRealmData), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $updateRealmData;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateRealm
     *
     * Update a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Admin\Model\UpdateRealmData|null $updateRealmData updateRealmData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\NotFoundError|\Lock\Client\OpenApi\Admin\Model\ValidationError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError
     */
    public function updateRealm($realm, $updateRealmData = null, string $contentType = self::contentTypes['updateRealm'][0])
    {
        list($response) = $this->updateRealmWithHttpInfo($realm, $updateRealmData, $contentType);
        return $response;
    }

    /**
     * Operation updateRealmWithHttpInfo
     *
     * Update a realm
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Admin\Model\UpdateRealmData|null $updateRealmData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRealm'] to see the possible values for this operation
     *
     * @throws \Lock\Client\OpenApi\Admin\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\OpenApi\Admin\Model\RealmResponse|\Lock\Client\OpenApi\Admin\Model\NotFoundError|\Lock\Client\OpenApi\Admin\Model\ValidationError|\Lock\Client\OpenApi\Admin\Model\AuthenticationError|\Lock\Client\OpenApi\Admin\Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateRealmWithHttpInfo($realm, $updateRealmData = null, string $contentType = self::contentTypes['updateRealm'][0])
    {
        $request = $this->updateRealmRequest($realm, $updateRealmData, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\NotFoundError',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\RealmResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\NotFoundError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthenticationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\OpenApi\Admin\Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'updateRealm'
     *
     * @param  string $realm The realm slug (required)
     * @param  \Lock\Client\OpenApi\Admin\Model\UpdateRealmData|null $updateRealmData (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRealm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateRealmRequest($realm, $updateRealmData = null, string $contentType = self::contentTypes['updateRealm'][0])
    {

        // verify the required parameter 'realm' is set
        if ($realm === null || (is_array($realm) && count($realm) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $realm when calling updateRealm'
            );
        }



        $resourcePath = '/v1/realms/{realm}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($realm !== null) {
            $resourcePath = str_replace(
                '{realm}',
                ObjectSerializer::toPathValue($realm),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateRealmData)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($updateRealmData), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $updateRealmData;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
