<?php
/**
 * TokensApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Lock\Client\Oidc
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lock API
 *
 * OAuth and OpenID Connect endpoints, discovery metadata, and the APIs for managing this Lock instance. Protocol endpoints are served on each realm’s own host.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lock\Client\Oidc\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Lock\Client\Oidc\ApiException;
use Lock\Client\Oidc\Configuration;
use Lock\Client\Oidc\HeaderSelector;
use Lock\Client\Oidc\ObjectSerializer;

/**
 * TokensApi Class Doc Comment
 *
 * @category Class
 * @package  Lock\Client\Oidc
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TokensApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'introspectToken' => [
            'application/x-www-form-urlencoded',
        ],
        'issueToken' => [
            'application/x-www-form-urlencoded',
        ],
        'revokeToken' => [
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation introspectToken
     *
     * Inspect a token
     *
     * @param  string $token token (required)
     * @param  string|null $clientId Required for form-secret and public-client authentication. Omit when using HTTP Basic. (optional)
     * @param  string|null $clientSecret Required only for client_secret_post. Never combine with HTTP Basic. (optional)
     * @param  string|null $tokenTypeHint access_token or refresh_token; unrecognized hints are ignored. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \Lock\Client\Oidc\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\Oidc\Model\TokenIntrospection|\Lock\Client\Oidc\Model\OAuthError|\Lock\Client\Oidc\Model\OAuthError
     */
    public function introspectToken($token, $clientId = null, $clientSecret = null, $tokenTypeHint = null, string $contentType = self::contentTypes['introspectToken'][0])
    {
        list($response) = $this->introspectTokenWithHttpInfo($token, $clientId, $clientSecret, $tokenTypeHint, $contentType);
        return $response;
    }

    /**
     * Operation introspectTokenWithHttpInfo
     *
     * Inspect a token
     *
     * @param  string $token (required)
     * @param  string|null $clientId Required for form-secret and public-client authentication. Omit when using HTTP Basic. (optional)
     * @param  string|null $clientSecret Required only for client_secret_post. Never combine with HTTP Basic. (optional)
     * @param  string|null $tokenTypeHint access_token or refresh_token; unrecognized hints are ignored. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \Lock\Client\Oidc\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\Oidc\Model\TokenIntrospection|\Lock\Client\Oidc\Model\OAuthError|\Lock\Client\Oidc\Model\OAuthError, HTTP status code, HTTP response headers (array of strings)
     */
    public function introspectTokenWithHttpInfo($token, $clientId = null, $clientSecret = null, $tokenTypeHint = null, string $contentType = self::contentTypes['introspectToken'][0])
    {
        $request = $this->introspectTokenRequest($token, $clientId, $clientSecret, $tokenTypeHint, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\Oidc\Model\TokenIntrospection',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\Oidc\Model\TokenIntrospection',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\TokenIntrospection',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'introspectToken'
     *
     * @param  string $token (required)
     * @param  string|null $clientId Required for form-secret and public-client authentication. Omit when using HTTP Basic. (optional)
     * @param  string|null $clientSecret Required only for client_secret_post. Never combine with HTTP Basic. (optional)
     * @param  string|null $tokenTypeHint access_token or refresh_token; unrecognized hints are ignored. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function introspectTokenRequest($token, $clientId = null, $clientSecret = null, $tokenTypeHint = null, string $contentType = self::contentTypes['introspectToken'][0])
    {

        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling introspectToken'
            );
        }





        $resourcePath = '/oauth/introspect';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new \Lock\Client\Oidc\FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
            'token' => $token,
            'token_type_hint' => $tokenTypeHint,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation issueToken
     *
     * Issue or exchange tokens
     *
     * @param \Lock\Client\Oidc\Model\AuthorizationCodeRequest|\Lock\Client\Oidc\Model\RefreshTokenRequest|\Lock\Client\Oidc\Model\ClientCredentialsRequest|\Lock\Client\Oidc\Model\TokenExchangeRequest $tokenRequest
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['issueToken'] to see the possible values for this operation
     *
     * @throws \Lock\Client\Oidc\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Lock\Client\Oidc\Model\TokenResponse|\Lock\Client\Oidc\Model\OAuthError|\Lock\Client\Oidc\Model\OAuthError|\Lock\Client\Oidc\Model\OAuthError
     */
    public function issueToken(\Lock\Client\Oidc\Model\AuthorizationCodeRequest|\Lock\Client\Oidc\Model\RefreshTokenRequest|\Lock\Client\Oidc\Model\ClientCredentialsRequest|\Lock\Client\Oidc\Model\TokenExchangeRequest $tokenRequest, string $contentType = self::contentTypes['issueToken'][0])
    {
        list($response) = $this->issueTokenWithHttpInfo($tokenRequest, $contentType);
        return $response;
    }

    /**
     * Operation issueTokenWithHttpInfo
     *
     * Issue or exchange tokens
     *
     * @param \Lock\Client\Oidc\Model\AuthorizationCodeRequest|\Lock\Client\Oidc\Model\RefreshTokenRequest|\Lock\Client\Oidc\Model\ClientCredentialsRequest|\Lock\Client\Oidc\Model\TokenExchangeRequest $tokenRequest
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['issueToken'] to see the possible values for this operation
     *
     * @throws \Lock\Client\Oidc\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Lock\Client\Oidc\Model\TokenResponse|\Lock\Client\Oidc\Model\OAuthError|\Lock\Client\Oidc\Model\OAuthError|\Lock\Client\Oidc\Model\OAuthError, HTTP status code, HTTP response headers (array of strings)
     */
    public function issueTokenWithHttpInfo(\Lock\Client\Oidc\Model\AuthorizationCodeRequest|\Lock\Client\Oidc\Model\RefreshTokenRequest|\Lock\Client\Oidc\Model\ClientCredentialsRequest|\Lock\Client\Oidc\Model\TokenExchangeRequest $tokenRequest, string $contentType = self::contentTypes['issueToken'][0])
    {
        $request = $this->issueTokenRequest($tokenRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\Oidc\Model\TokenResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Lock\Client\Oidc\Model\TokenResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\TokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'issueToken'
     *
     * @param \Lock\Client\Oidc\Model\AuthorizationCodeRequest|\Lock\Client\Oidc\Model\RefreshTokenRequest|\Lock\Client\Oidc\Model\ClientCredentialsRequest|\Lock\Client\Oidc\Model\TokenExchangeRequest $tokenRequest
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['issueToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function issueTokenRequest(\Lock\Client\Oidc\Model\AuthorizationCodeRequest|\Lock\Client\Oidc\Model\RefreshTokenRequest|\Lock\Client\Oidc\Model\ClientCredentialsRequest|\Lock\Client\Oidc\Model\TokenExchangeRequest $tokenRequest, string $contentType = self::contentTypes['issueToken'][0])
    {
        $invalidProperties = $tokenRequest->listInvalidProperties();
        if ($invalidProperties !== []) {
            throw new \InvalidArgumentException(implode('; ', $invalidProperties));
        }


        $resourcePath = '/oauth/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        $formDataProcessor = new \Lock\Client\Oidc\FormDataProcessor();
        $formData = $formDataProcessor->prepare((array) ObjectSerializer::sanitizeForSerialization($tokenRequest));
        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation revokeToken
     *
     * Revoke a token
     *
     * @param  string $token token (required)
     * @param  string|null $clientId Required for form-secret and public-client authentication. Omit when using HTTP Basic. (optional)
     * @param  string|null $clientSecret Required only for client_secret_post. Never combine with HTTP Basic. (optional)
     * @param  string|null $tokenTypeHint access_token or refresh_token; unrecognized hints are ignored. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeToken'] to see the possible values for this operation
     *
     * @throws \Lock\Client\Oidc\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function revokeToken($token, $clientId = null, $clientSecret = null, $tokenTypeHint = null, string $contentType = self::contentTypes['revokeToken'][0])
    {
        $this->revokeTokenWithHttpInfo($token, $clientId, $clientSecret, $tokenTypeHint, $contentType);
    }

    /**
     * Operation revokeTokenWithHttpInfo
     *
     * Revoke a token
     *
     * @param  string $token (required)
     * @param  string|null $clientId Required for form-secret and public-client authentication. Omit when using HTTP Basic. (optional)
     * @param  string|null $clientSecret Required only for client_secret_post. Never combine with HTTP Basic. (optional)
     * @param  string|null $tokenTypeHint access_token or refresh_token; unrecognized hints are ignored. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeToken'] to see the possible values for this operation
     *
     * @throws \Lock\Client\Oidc\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function revokeTokenWithHttpInfo($token, $clientId = null, $clientSecret = null, $tokenTypeHint = null, string $contentType = self::contentTypes['revokeToken'][0])
    {
        $request = $this->revokeTokenRequest($token, $clientId, $clientSecret, $tokenTypeHint, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Lock\Client\Oidc\Model\OAuthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Create request for operation 'revokeToken'
     *
     * @param  string $token (required)
     * @param  string|null $clientId Required for form-secret and public-client authentication. Omit when using HTTP Basic. (optional)
     * @param  string|null $clientSecret Required only for client_secret_post. Never combine with HTTP Basic. (optional)
     * @param  string|null $tokenTypeHint access_token or refresh_token; unrecognized hints are ignored. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function revokeTokenRequest($token, $clientId = null, $clientSecret = null, $tokenTypeHint = null, string $contentType = self::contentTypes['revokeToken'][0])
    {

        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling revokeToken'
            );
        }





        $resourcePath = '/oauth/revoke';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new \Lock\Client\Oidc\FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
            'token' => $token,
            'token_type_hint' => $tokenTypeHint,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
